---

baseurl:            http://blog.nilproductions.com/
pygmentsuseclasses: true 
theme:              hugo-incorporated
languageCode: en-us

params:
  inc:
    # Blog Information
    title:        "Josh Chase"
    subtitle:     "It's a blog!"
    cover_image:  blog-cover.jpg
    logo:         logo.png
    
    # Company information
    company:      nil productions 
    #url:          http://nilproductions.com/
#    facebook:     
    github:       Pursuit92
    twitter:      Pursuit92
#    gplus:        ''
    about_link:   /about
    
    # Product Information
    #product_link: http://nilproductions.com/
    #tagline:      "Coming up nil for quite some time."
    
    # Comments
    disqus:
      # Eg. "exampleblog" Set to false to disable comments
      #shortname:  "jecpw"
      shortname:  false
    
    # Sharing settings
    sharing:
      twitter:    true
      facebook:   false
      gplus:      false
      hn:         true
      
    
   # Analytics     
    analytics:
      google: false # Add tracking code in _includes/_google-analytics.html
#      piwik:
#        domain: piwik.nilproductions.com
#        siteid: 1  
        
    # Google Fonts
    # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
    google_font: 'Droid+Sans:400,700'
    
    # Setup your fonts, colors etc at _assets/stylesheets/main.scss
